<?php

use PhpCsFixer\Config;
use PhpCsFixer\Finder;

/**
 * Official-Based：官方全量配置
 * version:3.0
 * (官方)参考配置文档(更全更新)：https://github.com/FriendsOfPHP/PHP-CS-Fixer/tree/3.0/doc/rules
 * (推荐)参考配置文档(可读性高，同时支持版本切换和搜索)：https://mlocati.github.io/php-cs-fixer-configurator/#version:3.0
 * Q1:IDE中链式调用方法对齐的选项在php-cs-fixer中暂未找到对应参数.
 */
$rules = [
    /*------------------------------------------------------alias------------------------------------------------------*/
    'array_push'                                       => ' ',
    'backtick_to_shell_exec'                           => ' ',
    'ereg_to_preg'                                     => ' ',
    'mb_str_functions'                                 => ' ',
    'no_alias_functions'                               => ' ',
    'no_alias_language_construct_call'                 => ' ',
    'no_mixed_echo_print'                              => ' ',
    'pow_to_exponentiation'                            => ' ',
    'random_api_migration'                             => ' ',
    'set_type_to_cast'                                 => ' ',
    /*-------------------------------------------------array_notation-------------------------------------------------*/
    'array_syntax'                                     => ' ',
    'no_multiline_whitespace_around_double_arrow'      => ' ',
    'no_trailing_comma_in_singleline_array'            => ' ',
    'no_whitespace_before_comma_in_array'              => ' ',
    'normalize_index_brace'                            => ' ',
    'trim_array_spaces'                                => ' ',
    'whitespace_after_comma_in_array'                  => ' ',
    /*------------------------------------------------------basic------------------------------------------------------*/
    'braces'                                           => ' ',
    'encoding'                                         => ' ',
    'non_printable_character'                          => ' ',
    'psr_autoloading'                                  => ' ',
    /*-----------------------------------------------------casing-----------------------------------------------------*/
    'constant_case'                                    => ' ',
    'lowercase_keywords'                               => ' ',
    'lowercase_static_reference'                       => ' ',
    'magic_constant_casing'                            => ' ',
    'magic_method_casing'                              => ' ',
    'native_function_casing'                           => ' ',
    'native_function_type_declaration_casing'          => ' ',
    /*--------------------------------------------------cast_notation--------------------------------------------------*/
    'cast_spaces'                                      => ' ',
    'lowercase_cast'                                   => ' ',
    'modernize_types_casting'                          => ' ',
    'no_short_bool_cast'                               => ' ',
    'no_unset_cast'                                    => ' ',
    'short_scalar_cast'                                => ' ',
    /*-------------------------------------------------class_notation-------------------------------------------------*/
    'class_attributes_separation'                      => ' ',
    'class_definition'                                 => ' ',
    'final_class'                                      => ' ',
    'final_internal_class'                             => ' ',
    'final_public_method_for_abstract_class'           => ' ',
    'no_blank_lines_after_class_opening'               => ' ',
    'no_null_property_initialization'                  => ' ',
    'no_php4_constructor'                              => ' ',
    'no_unneeded_final_method'                         => ' ',
    'ordered_class_elements'                           => ' ',
    'ordered_interfaces'                               => ' ',
    'ordered_traits'                                   => ' ',
    'protected_to_private'                             => ' ',
    'self_accessor'                                    => ' ',
    'self_static_accessor'                             => ' ',
    'single_class_element_per_statement'               => ' ',
    'single_trait_insert_per_statement'                => ' ',
    'visibility_required'                              => ' ',
    /*---------------------------------------------------class_usage---------------------------------------------------*/
    'date_time_immutable'                              => ' ',
    /*-----------------------------------------------------comment-----------------------------------------------------*/
    'comment_to_phpdoc'                                => ' ',
    'header_comment'                                   => ' ',
    'multiline_comment_opening_closing'                => ' ',
    'no_empty_comment'                                 => ' ',
    'no_trailing_whitespace_in_comment'                => ' ',
    'single_line_comment_style'                        => ' ',
    /*------------------------------------------------constant_notation------------------------------------------------*/
    'native_constant_invocation'                       => ' ',
    /*------------------------------------------------control_structure------------------------------------------------*/
    'elseif'                                           => ' ',
    'include'                                          => ' ',
    'no_alternative_syntax'                            => ' ',
    'no_break_comment'                                 => ' ',
    'no_superfluous_elseif'                            => ' ',
    'no_trailing_comma_in_list_call'                   => ' ',
    'no_unneeded_control_parentheses'                  => ' ',
    'no_unneeded_curly_braces'                         => ' ',
    'no_useless_else'                                  => ' ',
    'simplified_if_return'                             => ' ',
    'switch_case_semicolon_to_colon'                   => ' ',
    'switch_case_space'                                => ' ',
    'switch_continue_to_break'                         => ' ',
    'trailing_comma_in_multiline'                      => ' ',
    'yoda_style'                                       => ' ',
    /*-----------------------------------------------doctrine_annotation-----------------------------------------------*/
    'doctrine_annotation_array_assignment'             => ' ',
    'doctrine_annotation_braces'                       => ' ',
    'doctrine_annotation_indentation'                  => ' ',
    'doctrine_annotation_spaces'                       => ' ',
    /*------------------------------------------------function_notation------------------------------------------------*/
    'combine_nested_dirname'                           => ' ',
    'fopen_flag_order'                                 => ' ',
    'fopen_flags'                                      => ' ',
    'function_declaration'                             => ' ',
    'function_typehint_space'                          => ' ',
    'implode_call'                                     => ' ',
    'lambda_not_used_import'                           => ' ',
    'method_argument_space'                            => ' ',
    'native_function_invocation'                       => ' ',
    'no_spaces_after_function_name'                    => ' ',
    'no_unreachable_default_argument_value'            => ' ',
    'no_useless_sprintf'                               => ' ',
    'nullable_type_declaration_for_default_null_value' => ' ',
    'phpdoc_to_param_type'                             => ' ',
    'phpdoc_to_property_type'                          => ' ',
    'phpdoc_to_return_type'                            => ' ',
    'regular_callable_call'                            => ' ',
    'return_type_declaration'                          => ' ',
    'single_line_throw'                                => ' ',
    'static_lambda'                                    => ' ',
    'use_arrow_functions'                              => ' ',
    'void_return'                                      => ' ',
    /*-----------------------------------------------------import-----------------------------------------------------*/
    'fully_qualified_strict_types'                     => ' ',
    'global_namespace_import'                          => ' ',
    'group_import'                                     => ' ',
    'no_leading_import_slash'                          => ' ',
    'no_unused_imports'                                => ' ',
    'ordered_imports'                                  => ' ',
    'single_import_per_statement'                      => ' ',
    'single_line_after_imports'                        => ' ',
    /*------------------------------------------------language_construct------------------------------------------------*/
    'class_keyword_remove'                             => ' ',
    'combine_consecutive_issets'                       => ' ',
    'combine_consecutive_unsets'                       => ' ',
    'declare_equal_normalize'                          => ' ',
    'dir_constant'                                     => ' ',
    'error_suppression'                                => ' ',
    'explicit_indirect_variable'                       => ' ',
    'function_to_constant'                             => ' ',
    'is_null'                                          => ' ',
    'no_unset_on_property'                             => ' ',
    'single_space_after_construct'                     => ' ',
    /*--------------------------------------------------list_notation--------------------------------------------------*/
    'list_syntax'                                      => ' ',
    /*-----------------------------------------------namespace_notation-----------------------------------------------*/
    'blank_line_after_namespace'                       => ' ',
    'clean_namespace'                                  => ' ',
    'no_blank_lines_before_namespace'                  => ' ',
    'no_leading_namespace_whitespace'                  => ' ',
    'single_blank_line_before_namespace'               => ' ',
    /*-----------------------------------------------------naming-----------------------------------------------------*/
    'no_homoglyph_names'                               => ' ',
    /*----------------------------------------------------operator----------------------------------------------------*/
    'binary_operator_spaces'                           => ' ',
    'concat_space'                                     => ' ',
    'increment_style'                                  => ' ',
    'logical_operators'                                => ' ',
    'new_with_braces'                                  => ' ',
    'not_operator_with_space'                          => ' ',
    'not_operator_with_successor_space'                => ' ',
    'object_operator_without_whitespace'               => ' ',
    'operator_linebreak'                               => ' ',
    'standardize_increment'                            => ' ',
    'standardize_not_equals'                           => ' ',
    'ternary_operator_spaces'                          => ' ',
    'ternary_to_elvis_operator'                        => ' ',
    'ternary_to_null_coalescing'                       => ' ',
    'unary_operator_spaces'                            => ' ',
    /*-----------------------------------------------------php_tag-----------------------------------------------------*/
    'blank_line_after_opening_tag'                     => ' ',
    'echo_tag_syntax'                                  => ' ',
    'full_opening_tag'                                 => ' ',
    'linebreak_after_opening_tag'                      => ' ',
    'no_closing_tag'                                   => ' ',
    /*----------------------------------------------------php_unit----------------------------------------------------*/
    'php_unit_construct'                               => ' ',
    'php_unit_dedicate_assert'                         => ' ',
    'php_unit_dedicate_assert_internal_type'           => ' ',
    'php_unit_expectation'                             => ' ',
    'php_unit_fqcn_annotation'                         => ' ',
    'php_unit_internal_class'                          => ' ',
    'php_unit_method_casing'                           => ' ',
    'php_unit_mock'                                    => ' ',
    'php_unit_mock_short_will_return'                  => ' ',
    'php_unit_namespaced'                              => ' ',
    'php_unit_no_expectation_annotation'               => ' ',
    'php_unit_set_up_tear_down_visibility'             => ' ',
    'php_unit_size_class'                              => ' ',
    'php_unit_strict'                                  => ' ',
    'php_unit_test_annotation'                         => ' ',
    'php_unit_test_case_static_method_calls'           => ' ',
    'php_unit_test_class_requires_covers'              => ' ',
    /*-----------------------------------------------------phpdoc-----------------------------------------------------*/
    'align_multiline_comment'                          => ' ',
    'general_phpdoc_annotation_remove'                 => ' ',
    'general_phpdoc_tag_rename'                        => ' ',
    'no_blank_lines_after_phpdoc'                      => ' ',
    'no_empty_phpdoc'                                  => ' ',
    'no_superfluous_phpdoc_tags'                       => ' ',
    'phpdoc_add_missing_param_annotation'              => ' ',
    'phpdoc_align'                                     => ' ',
    'phpdoc_annotation_without_dot'                    => ' ',
    'phpdoc_indent'                                    => ' ',
    'phpdoc_inline_tag_normalizer'                     => ' ',
    'phpdoc_line_span'                                 => ' ',
    'phpdoc_no_access'                                 => ' ',
    'phpdoc_no_alias_tag'                              => ' ',
    'phpdoc_no_empty_return'                           => ' ',
    'phpdoc_no_package'                                => ' ',
    'phpdoc_no_useless_inheritdoc'                     => ' ',
    'phpdoc_order_by_value'                            => ' ',
    'phpdoc_order'                                     => ' ',
    'phpdoc_return_self_reference'                     => ' ',
    'phpdoc_scalar'                                    => ' ',
    'phpdoc_separation'                                => ' ',
    'phpdoc_single_line_var_spacing'                   => ' ',
    'phpdoc_summary'                                   => ' ',
    'phpdoc_tag_casing'                                => ' ',
    'phpdoc_tag_type'                                  => ' ',
    'phpdoc_to_comment'                                => ' ',
    'phpdoc_trim_consecutive_blank_line_separation'    => ' ',
    'phpdoc_trim'                                      => ' ',
    'phpdoc_types'                                     => ' ',
    'phpdoc_types_order'                               => ' ',
    'phpdoc_var_annotation_correct_order'              => ' ',
    'phpdoc_var_without_name'                          => ' ',
    /*-------------------------------------------------return_notation-------------------------------------------------*/
    'no_useless_return'                                => ' ',
    'return_assignment'                                => ' ',
    'simplified_null_return'                           => ' ',
    /*----------------------------------------------------semicolon----------------------------------------------------*/
    'multiline_whitespace_before_semicolons'           => ' ',
    'no_empty_statement'                               => ' ',
    'no_singleline_whitespace_before_semicolons'       => ' ',
    'semicolon_after_instruction'                      => ' ',
    'space_after_semicolon'                            => ' ',
    /*-----------------------------------------------------strict-----------------------------------------------------*/
    'declare_strict_types'                             => ' ',
    'strict_comparison'                                => ' ',
    'strict_param'                                     => ' ',
    /*-------------------------------------------------strict_notation-------------------------------------------------*/
    'escape_implicit_backslashes'                      => ' ',
    'explicit_string_variable'                         => ' ',
    'heredoc_to_nowdoc'                                => ' ',
    'no_binary_string'                                 => ' ',
    'no_trailing_whitespace_in_string'                 => ' ',
    'simple_to_complex_string_variable'                => ' ',
    'single_quote'                                     => ' ',
    'string_line_ending'                               => ' ',
    /*---------------------------------------------------whitespace---------------------------------------------------*/
    'array_indentation'                                => ' ',
    'blank_line_before_statement'                      => ' ',
    'compact_nullable_typehint'                        => ' ',
    'heredoc_indentation'                              => ' ',
    'indentation_type'                                 => ' ',
    'line_ending'                                      => ' ',
    'method_chaining_indentation'                      => ' ',
    'no_extra_blank_lines'                             => ' ',
    'no_spaces_around_offset'                          => ' ',
    'no_spaces_inside_parenthesis'                     => ' ',
    'no_trailing_whitespace'                           => ' ',
    'no_whitespace_in_blank_line'                      => ' ',
    'single_blank_line_at_eof'                         => ' ',
];

$finder = Finder::create()
                ->in(__DIR__)
                ->name('*.php')
                ->notName('*.blade.php')
                ->ignoreDotFiles(true)
                ->ignoreVCS(true);

return Config::create()
             ->setFinder($finder)
             ->setRules($rules)
             ->setRiskyAllowed(true)
             ->setUsingCache(true);
